apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.data.fullname" . }}
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 9200
      targetPort: http
    - name: tcp-transport
      port: 9300
      targetPort: transport
      nodePort: null
  selector: {{- include "elasticsearch.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: data
