apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-filebeat-modules
  namespace: elk
  labels:
    k8s-app: filebeat
data:
  nginx.yml: |-
    - module: nginx
      # Access logs
      access:
        enabled: true
        #var.paths
        
      # Error logs
      error:
        enables: true
        #var.paths
