kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elasticsearch-storageclass
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - asia-east1-a
    - asia-east1-b
    - asia-east1-c
