apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app-name nginx-filebeat
  namespace: elk
  labels:
    app.kubernetes.io/name: *app-name
    app: *app-name
    component: elk-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-filebeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *app-name
        app: *app-name
        component: elk-beat
    spec:
      serviceAccountName: elk
      terminationGracePeriodSeconds: 30
      # Schedule nginx-filebeat with nginx-ingress-controller
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-ingress
              - key: component
                operator: In
                values:
                - controller
            topologyKey: "kubernetes.io/hostname"
            namespaces: # Namespace of target nginx-ingress-controller pod
              - default
              - nginx-ingress
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.3.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ELASTICSEARCH_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: ELASTICSEARCH_PROTOCOL
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: ELASTICSEARCH_PORT
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: elk-credentials
              key: ELASTICSEARCH_ELASTIC_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elk-credentials
              key: ELASTICSEARCH_ELASTIC_PASSWORD
        - name: KIBANA_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: KIBANA_PROTOCOL
        - name: KIBANA_HOST
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: KIBANA_HOST
        - name: KIBANA_PORT
          valueFrom:
            configMapKeyRef:
              name: elk-config
              key: KIBANA_PORT
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 20m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: elk-client-certificates
          mountPath: /etc/elk/certificates
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: nginx-filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: elk-client-certificates
        secret:
          secretName: elk-client-certificates
